export const ActionTypes = {
  // Movies
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_ERROR: "FETCH_MOVIES_ERROR",

  // Detail
  FETCH_DETAIL_START: "FETCH_DETAIL_START",
  FETCH_DETAIL_SUCCESS: "FETCH_DETAIL_SUCCESS",
  FETCH_DETAIL_ERROR: "FETCH_DETAIL_ERROR",

  // Series
  FETCH_SERIES_START: "FETCH_SERIES_START",
  FETCH_SERIES_SUCCESS: "FETCH_SERIES_SUCCESS",
  FETCH_SERIES_ERROR: "FETCH_SERIES_ERROR",

  // Search
  SEARCH_START: "SEARCH_START",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  SEARCH_ERROR: "SEARCH_ERROR",

  // Watchlist
  ADD_TO_WATCHLIST: "ADD_TO_WATCHLIST",
  REMOVE_FROM_WATCHLIST: "REMOVE_FROM_WATCHLIST",
  SET_WATCHLIST: "SET_WATCHLIST",

  // Genres
  FETCH_GENRES_START: "FETCH_GENRES_START",
  FETCH_GENRES_SUCCESS: "FETCH_GENRES_SUCCESS",
  FETCH_GENRES_ERROR: "FETCH_GENRES_ERROR",
};
